version: "3"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOAD_DIR}:/downloads
    expose:
      - "7878"
    restart: unless-stopped
    depends_on: 
      - jackett
      - qbittorrent
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.rule: PathPrefix(`/radarr`)
      traefik.http.routers.radarr.entrypoints: "http"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${TV_DIR}:/tv
      - ${DOWNLOAD_DIR}:/downloads
    expose:
      - "8989"
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.entrypoints: "http"
      traefik.http.routers.sonarr.rule: PathPrefix(`/sonarr`)
    depends_on:
      - jackett
      - qbittorrent

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment: 
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes: 
      - ${CONFIG_DIR}/lidarr:/config
      - ${MUSIC_DIR}:/music
      - ${DOWNLOAD_DIR}:/downloads
    expose:
      - "8686"
    labels:
      traefik.enable: "true"
      traefik.http.routers.lidarr.entrypoints: "http"
      traefik.http.routers.lidarr.rule: PathPrefix(`/lidarr`)
    depends_on: 
      - jackett
      - qbittorrent

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.jackett.entrypoints: "http"
      traefik.http.routers.jackett.rule: PathPrefix(`/jackett`)
      com.centurylinklabs.watchtower.enable: "true"

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment: 
      PUID: ${UID}
      PGID: ${GID}
      VERSION: docker
      TZ: ${TZ}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes: 
      - ${TV_DIR}:/tv
      - ${MUSIC_DIR}:/music
      - ${MOVIES_DIR}:/movies
      - ${CONFIG_DIR}/plex:/config
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment: 
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes: 
      - ${CONFIG_DIR}/tautulli:/config
    expose: 
      - "8181"
    labels:
      traefik.enable: "true"
      traefik.http.routers.tautulli.entrypoints: "http"
      traefik.http.routers.tautulli.rule: PathPrefix(`/stats`)
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    depends_on:
     - plex
  
  samba:
    image: dperson/samba
    container_name: samba
    ports: 
      - 139:139
      - 445:445
    environment: 
      TZ: ${TZ}
      USER: ${SMBUSER};${SMBPASSWORD}
      RECYCLE: 'false'
      SHARE: Peliculas;/movies;yes;no;no;mediacenter
      SHARE2: Musica;/music;yes;no;no;mediacenter
      SHARE3: Series;/tv;yes;no;no;mediacenter
    volumes: 
      - ${TV_DIR}:/tv
      - ${MUSIC_DIR}:/music
      - ${MOVIES_DIR}:/movies
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    expose:
      - "3579"
    environment: 
        PUID: ${UID}
        PGID: ${GID}
        TZ: ${TZ}
    volumes: 
        - ${CONFIG_DIR}/ombi:/config
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.ombi.entrypoints: "http,external"
      traefik.http.routers.ombi.rule: PathPrefix(`/`)
      com.centurylinklabs.watchtower.enable: "true"

  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${CONFIG_DIR}/traefik:/etc/traefik"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
