version: "3"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on: 
      - jackett
      - qbittorrent

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${TV_DIR}:/tv
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - jackett
      - qbittorrent

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment: 
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes: 
      - ${CONFIG_DIR}/lidarr:/config
      - ${MUSIC_DIR}:/music
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 8686:8686
    depends_on: 
      - jackett
      - qbittorrent

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

#  deluge:
#    image: linuxserver/deluge
#    container_name: deluge
#    network_mode: host
#    environment:
#      PUID: ${UID}
#      PGID: ${GID}
#      TZ: ${TZ}
#    volumes:
#      - ${CONFIG_DIR}/deluge:/config
#      - ${DOWNLOAD_DIR}:/downloads
#    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    restart: unless-stopped
    depends_on:
     - jackett

  plex:
    image: linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment: 
      PUID: ${UID}
      PGID: ${GID}
      VERSION: docker
      TZ: ${TZ}
    volumes: 
      - ${TV_DIR}:/tv
      - ${MUSIC_DIR}:/music
      - ${MOVIES_DIR}:/movies
      - ${CONFIG_DIR}/plex:/config
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment: 
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes: 
      - ${CONFIG_DIR}/tautulli:/config
    ports: 
      - 8181:8181
    restart: unless-stopped
    depends_on:
     - plex

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment: 
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TZ}
    volumes: 
      - ${CONFIG_DIR}/heimdall:/config
    ports: 
      - 80:80
      - 443:443
    restart: unless-stopped

  # jellyfin:
  #   image: linuxserver/jellyfin:bionic
  #   container_name: jellyfin
  #   network_mode: host
  #   environment: 
  #     PUID: ${UID}
  #     PGID: ${GID}
  #     TZ: ${TZ}
  #   volumes: 
  #     - ${TV_DIR}:/tv
  #     - ${MUSIC_DIR}:/music
  #     - ${MOVIES_DIR}:/movies
  #     - ${CONFIG_DIR}/jellyfin:/config
  #   restart: unless-stopped
